#-------------------------------
# General Site Settings

title: Zijing Wu
logo: 
author: zj

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hi! 你好呀! <br> I'm Zijing =))

social:
- {icon: "ti-instagram", link: "https://www.instagram.com/zjwiiiii/"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  Welcome! I am new to writing but I plan to publish a new article every 2 weeks to share interests and ideas. Maybe also some one liners when I want to rant lol <br>
  欢迎欢迎！这是我第一次试图写东西，尽量每两周更一篇文章，分享我最近的所见所闻所思所爱. 当然也有可能加点小吐槽~

blurb-btn-link: '/about'
blurb-btn-name: more about me ? 我是谁

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: wzjinsg@gmail.com